namespace Team17.Online.Multiplayer.Messaging
{
	public enum MessageType
	{
		Example = 0,
		LevelLoadByIndex = 1,
		LevelLoadByName = 2,
		EntitySynchronisation = 3,
		EntityEvent = 4,
		SpawnEntity = 5,
		DestroyEntity = 6,
		ChefOwnership = 7,
		UsersChanged = 8,
		UsersAdded = 9,
		Input = 10,
		GameState = 11,
		ChefAvatar = 12,
		LatencyMeasure = 13,
		TimeSync = 14,
		ControllerSettings = 15,
		TriggerEvent = 16,
		LobbyServer = 17,
		LobbyClient = 18,
		ChefEvent = 19,
		ChefEffect = 20,
		MapAvatar = 21,
		MapAvatarHorn = 22,
		DynamicLevel = 23,
		GameSetup = 24,
		GameProgressData = 25,
		EmoteWheel = 26,
		SetupCoopSession = 27,
		FlowInput = 28,
		Achievement = 29,
		TriggerAudio = 30,
		SpawnPhysicalAttachment = 31,
		ResumeWorldObjectSync = 32,
		ResumeChefPositionSync = 33,
		ResumePhysicsObjectSync = 34,
		BossLevel = 35,
		DestroyChef = 36,
		HighScores = 37,
		DestroyEntities = 38,
		ResumeEntitySync = 39,
		SessionConfigSync = 40,
		HordeSpawn = 41,
		COUNT = 42
	}
}
